import type {
  User,
  Product,
  Order,
  Transaction,
  GachaPool,
  GachaItem,
  GachaPull,
  Review,
  Notification,
} from './types'

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'buyer@example.com',
    username: 'buyer001',
    displayName: 'นักช้อป',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=buyer',
    role: 'buyer',
    balance: 5000,
    kycStatus: 'verified',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-03-01T08:00:00Z',
    tier: 'bronze',
    lifetimePoints: 0,
    balancePoints: 0,
    lastActivityAt: '2024-03-01T08:00:00Z',
  },
  {
    id: 'user-2',
    email: 'seller@example.com',
    username: 'topseller',
    displayName: 'ร้าน TopSeller',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=seller',
    role: 'seller',
    balance: 25000,
    kycStatus: 'verified',
    createdAt: '2023-06-01T10:00:00Z',
    updatedAt: '2024-03-10T12:00:00Z',
    tier: 'gold',
    lifetimePoints: 0,
    balancePoints: 0,
    lastActivityAt: '2024-03-10T12:00:00Z',
  },
  {
    id: 'user-3',
    email: 'admin@example.com',
    username: 'admin',
    displayName: 'Admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
    role: 'admin',
    balance: 0,
    kycStatus: 'verified',
    createdAt: '2023-01-01T10:00:00Z',
    updatedAt: '2024-03-15T10:00:00Z',
    tier: 'vip',
    lifetimePoints: 0,
    balancePoints: 0,
    lastActivityAt: '2024-03-15T10:00:00Z',
  },
]

// ==================== Mock Products ====================
export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    sellerId: 'user-2',
    sellerName: 'ร้าน TopSeller',
    title: 'ไอดี ROV แรงค์ Conqueror Season 30',
    description: 'ไอดี ROV ระดับ Conqueror มีฮีโร่ครบ 100+ ตัว สกินหายากมากมาย พร้อมเล่นทันที',
    price: 8500,
    originalPrice: 12000,
    category: 'rov',
    type: 'account',
    status: 'available',
    images: [
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop',
    ],
    details: {
      'แรงค์': 'Conqueror',
      'จำนวนฮีโร่': '105',
      'จำนวนสกิน': '200+',
      'เพชร': '5,000',
    },
    tags: ['rov', 'conqueror', 'ไอดีแรง', 'สกินหายาก'],
    views: 1250,
    createdAt: '2024-02-20T10:00:00Z',
    updatedAt: '2024-03-01T08:00:00Z',
  },
  {
    id: 'prod-2',
    sellerId: 'user-2',
    sellerName: 'ร้าน TopSeller',
    title: 'ไอดี Free Fire แรงค์ Heroic ฟูลสกิน',
    description: 'ไอดี Free Fire ระดับ Heroic สกินปืนหายาก ชุดหายาก พร้อมเพชรในเกม',
    price: 4500,
    category: 'freefire',
    type: 'account',
    status: 'available',
    images: [
      'https://images.unsplash.com/photo-1552820728-8b83bb6b2b0d?w=400&h=300&fit=crop',
    ],
    details: {
      'แรงค์': 'Heroic',
      'เพชร': '2,000',
      'สกินปืน': '50+',
      'ชุด': '30+',
    },
    tags: ['freefire', 'heroic', 'สกินหายาก'],
    views: 890,
    createdAt: '2024-02-25T14:00:00Z',
    updatedAt: '2024-03-05T10:00:00Z',
  },
  {
    id: 'prod-3',
    sellerId: 'user-2',
    sellerName: 'ร้าน TopSeller',
    title: 'ไอดี eFootball มีผู้เล่นระดับ Legend',
    description: 'ไอดี eFootball 2024 มีผู้เล่น Legend หลายคน ทีมแข็งแกร่ง พร้อมลงสนาม',
    price: 3200,
    category: 'efootball',
    type: 'account',
    status: 'available',
    images: [
      'https://images.unsplash.com/photo-1493711662062-fa541f7f3d24?w=400&h=300&fit=crop',
    ],
    details: {
      'Rating': '4,500+',
      'ผู้เล่น Legend': '8',
      'ผู้เล่น Epic': '15',
      'GP': '500,000',
    },
    tags: ['efootball', 'legend', 'ทีมแข็ง'],
    views: 650,
    createdAt: '2024-03-01T09:00:00Z',
    updatedAt: '2024-03-10T16:00:00Z',
  },
  {
    id: 'prod-4',
    sellerId: 'user-2',
    sellerName: 'ร้าน TopSeller',
    title: 'ไอดี Genshin Impact AR 60 มี 5 ดาวเยอะ',
    description: 'ไอดี Genshin AR60 มีตัวละคร 5 ดาว 15+ ตัว อาวุธ 5 ดาว หลายชิ้น',
    price: 15000,
    originalPrice: 20000,
    category: 'genshin',
    type: 'account',
    status: 'available',
    images: [
      'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=300&fit=crop',
    ],
    details: {
      'AR': '60',
      'ตัวละคร 5 ดาว': '15',
      'อาวุธ 5 ดาว': '8',
      'Primogems': '10,000',
    },
    tags: ['genshin', 'ar60', '5star', 'ไอดีแรง'],
    views: 2100,
    createdAt: '2024-02-10T11:00:00Z',
    updatedAt: '2024-03-12T14:00:00Z',
  },
  {
    id: 'prod-5',
    sellerId: 'user-2',
    sellerName: 'ร้าน TopSeller',
    title: 'ไอดี PUBG Mobile Conqueror Asia',
    description: 'ไอดี PUBG Mobile แรงค์ Conqueror Server Asia สกินปืนหายาก ชุดหายาก',
    price: 6800,
    category: 'pubg',
    type: 'account',
    status: 'available',
    images: [
      'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=400&h=300&fit=crop',
    ],
    details: {
      'แรงค์': 'Conqueror',
      'Server': 'Asia',
      'UC': '3,000',
      'สกิน M416': 'Glacier',
    },
    tags: ['pubg', 'conqueror', 'asia', 'glacier'],
    views: 1450,
    createdAt: '2024-02-28T15:00:00Z',
    updatedAt: '2024-03-08T11:00:00Z',
  },
  {
    id: 'prod-6',
    sellerId: 'user-2',
    sellerName: 'ร้าน TopSeller',
    title: 'สกิน ROV Murad Cyber Soul',
    description: 'สกินหายาก Murad Cyber Soul ส่งผ่าน Gift หรือแลกบัญชี',
    price: 1500,
    category: 'rov',
    type: 'skin',
    status: 'available',
    images: [
      'https://images.unsplash.com/photo-1542751110-97427bbecf20?w=400&h=300&fit=crop',
    ],
    details: {
      'ฮีโร่': 'Murad',
      'ชื่อสกิน': 'Cyber Soul',
      'ประเภท': 'Limited',
    },
    tags: ['rov', 'murad', 'skin', 'limited'],
    views: 780,
    createdAt: '2024-03-05T10:00:00Z',
    updatedAt: '2024-03-10T09:00:00Z',
  },
]

// ==================== Mock Orders ====================
export const mockOrders: Order[] = [
  {
    id: 'order-1',
    productId: 'prod-1',
    productTitle: 'ไอดี ROV แรงค์ Conqueror Season 30',
    productImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop',
    buyerId: 'user-1',
    buyerName: 'นักช้อป',
    sellerId: 'user-2',
    sellerName: 'ร้าน TopSeller',
    amount: 8500,
    platformFee: 425,
    sellerReceives: 8075,
    status: 'completed',
    deliveryInfo: 'รหัส: abc123, รหัสผ่าน: xxx',
    createdAt: '2024-02-25T10:00:00Z',
    updatedAt: '2024-02-26T14:00:00Z',
  },
  {
    id: 'order-2',
    productId: 'prod-2',
    productTitle: 'ไอดี Free Fire แรงค์ Heroic ฟูลสกิน',
    productImage: 'https://images.unsplash.com/photo-1552820728-8b83bb6b2b0d?w=400&h=300&fit=crop',
    buyerId: 'user-1',
    buyerName: 'นักช้อป',
    sellerId: 'user-2',
    sellerName: 'ร้าน TopSeller',
    amount: 4500,
    platformFee: 225,
    sellerReceives: 4275,
    status: 'processing',
    createdAt: '2024-03-10T15:00:00Z',
    updatedAt: '2024-03-10T16:00:00Z',
  },
]

// ==================== Mock Transactions ====================
export const mockTransactions: Transaction[] = [
  {
    id: 'txn-1',
    userId: 'user-1',
    type: 'deposit',
    amount: 10000,
    balanceBefore: 0,
    balanceAfter: 10000,
    status: 'completed',
    description: 'เติมเงินผ่าน PromptPay',
    createdAt: '2024-02-20T10:00:00Z',
  },
  {
    id: 'txn-2',
    userId: 'user-1',
    type: 'purchase',
    amount: -8500,
    balanceBefore: 10000,
    balanceAfter: 1500,
    status: 'completed',
    description: 'ซื้อ: ไอดี ROV แรงค์ Conqueror',
    referenceId: 'order-1',
    createdAt: '2024-02-25T10:00:00Z',
  },
  {
    id: 'txn-3',
    userId: 'user-2',
    type: 'sale',
    amount: 8075,
    balanceBefore: 16925,
    balanceAfter: 25000,
    status: 'completed',
    description: 'ขาย: ไอดี ROV แรงค์ Conqueror (หักค่าธรรมเนียม 5%)',
    referenceId: 'order-1',
    createdAt: '2024-02-26T14:00:00Z',
  },
  {
    id: 'txn-4',
    userId: 'user-1',
    type: 'deposit',
    amount: 5000,
    balanceBefore: 1500,
    balanceAfter: 6500,
    status: 'completed',
    description: 'เติมเงินผ่านธนาคาร',
    createdAt: '2024-03-05T09:00:00Z',
  },
  {
    id: 'txn-5',
    userId: 'user-1',
    type: 'gacha',
    amount: -500,
    balanceBefore: 6500,
    balanceAfter: 6000,
    status: 'completed',
    description: 'สุ่มตู้: ROV Lucky Box',
    createdAt: '2024-03-08T20:00:00Z',
  },
]

// ==================== Mock Gacha Pools ====================
export const mockGachaPools: GachaPool[] = [
  {
    id: 'gacha-1',
    name: 'ROV Lucky Box',
    nameTh: 'กล่องสุ่ม ROV',
    description: 'Win rare ROV skins and heroes!',
    descriptionTh: 'ลุ้นสกินและฮีโร่หายาก ROV!',
    category: 'rov',
    price: 99,
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop',
    isActive: true,
    items: [],
    totalPulls: 15420,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'gacha-2',
    name: 'Free Fire Diamond Box',
    nameTh: 'กล่องเพชร Free Fire',
    description: 'Get diamonds and exclusive items!',
    descriptionTh: 'รับเพชรและไอเทมพิเศษ!',
    category: 'freefire',
    price: 79,
    image: 'https://images.unsplash.com/photo-1552820728-8b83bb6b2b0d?w=400&h=300&fit=crop',
    isActive: true,
    items: [],
    totalPulls: 8930,
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'gacha-3',
    name: 'Genshin Wish Box',
    nameTh: 'กล่องอธิษฐาน Genshin',
    description: 'Pull for 5-star characters and weapons!',
    descriptionTh: 'ลุ้นตัวละครและอาวุธ 5 ดาว!',
    category: 'genshin',
    price: 149,
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=300&fit=crop',
    isActive: true,
    items: [],
    totalPulls: 22150,
    createdAt: '2024-02-01T00:00:00Z',
  },
]

// ==================== Mock Gacha Items ====================
export const mockGachaItems: GachaItem[] = [
  // ROV Lucky Box Items
  { id: 'gi-1', poolId: 'gacha-1', name: '100 Gems', nameTh: '100 เพชร', rarity: 'common', dropRate: 40, image: '', value: 50 },
  { id: 'gi-2', poolId: 'gacha-1', name: '500 Gems', nameTh: '500 เพชร', rarity: 'rare', dropRate: 30, image: '', value: 200 },
  { id: 'gi-3', poolId: 'gacha-1', name: 'Random Hero', nameTh: 'ฮีโร่สุ่ม', rarity: 'epic', dropRate: 20, image: '', value: 500 },
  { id: 'gi-4', poolId: 'gacha-1', name: 'Limited Skin', nameTh: 'สกินหายาก', rarity: 'legendary', dropRate: 10, image: '', value: 2000 },
  // Free Fire Items
  { id: 'gi-5', poolId: 'gacha-2', name: '50 Diamonds', nameTh: '50 เพชร', rarity: 'common', dropRate: 45, image: '', value: 30 },
  { id: 'gi-6', poolId: 'gacha-2', name: '200 Diamonds', nameTh: '200 เพชร', rarity: 'rare', dropRate: 30, image: '', value: 100 },
  { id: 'gi-7', poolId: 'gacha-2', name: 'Gun Skin Box', nameTh: 'กล่องสกินปืน', rarity: 'epic', dropRate: 18, image: '', value: 400 },
  { id: 'gi-8', poolId: 'gacha-2', name: 'Exclusive Bundle', nameTh: 'ชุดพิเศษ', rarity: 'legendary', dropRate: 7, image: '', value: 1500 },
  // Genshin Items
  { id: 'gi-9', poolId: 'gacha-3', name: '160 Primogems', nameTh: '160 Primogems', rarity: 'common', dropRate: 35, image: '', value: 80 },
  { id: 'gi-10', poolId: 'gacha-3', name: '800 Primogems', nameTh: '800 Primogems', rarity: 'rare', dropRate: 30, image: '', value: 300 },
  { id: 'gi-11', poolId: 'gacha-3', name: '4-Star Character', nameTh: 'ตัวละคร 4 ดาว', rarity: 'epic', dropRate: 25, image: '', value: 800 },
  { id: 'gi-12', poolId: 'gacha-3', name: '5-Star Character', nameTh: 'ตัวละคร 5 ดาว', rarity: 'legendary', dropRate: 10, image: '', value: 5000 },
]

// ==================== Mock Gacha Pulls ====================
export const mockGachaPulls: GachaPull[] = [
  {
    id: 'pull-1',
    poolId: 'gacha-1',
    userId: 'user-1',
    itemId: 'gi-2',
    item: mockGachaItems.find(i => i.id === 'gi-2')!,
    seed: 'abc123xyz',
    createdAt: '2024-03-08T20:00:00Z',
  },
]

// ==================== Mock Reviews ====================
export const mockReviews: Review[] = [
  {
    id: 'review-1',
    orderId: 'order-1',
    buyerId: 'user-1',
    buyerName: 'นักช้อป',
    buyerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=buyer',
    sellerId: 'user-2',
    rating: 5,
    comment: 'สินค้าตรงปก ผู้ขายตอบไว ส่งรหัสเร็วมาก แนะนำครับ!',
    createdAt: '2024-02-27T10:00:00Z',
  },
  {
    id: 'review-2',
    orderId: 'order-0',
    buyerId: 'user-0',
    buyerName: 'GameLover99',
    buyerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=gamelover',
    sellerId: 'user-2',
    rating: 4,
    comment: 'ไอดีดี คุ้มราคา แต่ต้องรอนิดนึง',
    createdAt: '2024-02-15T14:00:00Z',
  },
]

// ==================== Mock Notifications ====================
export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-1',
    type: 'order',
    title: 'Order Completed',
    titleTh: 'คำสั่งซื้อเสร็จสิ้น',
    message: 'Your order #order-1 has been completed.',
    messageTh: 'คำสั่งซื้อ #order-1 เสร็จสิ้นแล้ว',
    isRead: true,
    link: '/orders/order-1',
    createdAt: '2024-02-26T14:00:00Z',
  },
  {
    id: 'notif-2',
    userId: 'user-1',
    type: 'gacha',
    title: 'You won a rare item!',
    titleTh: 'คุณได้รับไอเทมหายาก!',
    message: 'Congratulations! You got 500 Gems from ROV Lucky Box.',
    messageTh: 'ยินดีด้วย! คุณได้รับ 500 เพชร จากกล่องสุ่ม ROV',
    isRead: false,
    createdAt: '2024-03-08T20:00:00Z',
  },
  {
    id: 'notif-3',
    userId: 'user-2',
    type: 'payment',
    title: 'Payment Received',
    titleTh: 'ได้รับเงินแล้ว',
    message: 'You received 8,075 THB from order #order-1.',
    messageTh: 'คุณได้รับเงิน 8,075 บาท จากคำสั่งซื้อ #order-1',
    isRead: false,
    link: '/dashboard/orders',
    createdAt: '2024-02-26T14:00:00Z',
  },
]

// ==================== Category Stats ====================
export const categoryStats = {
  rov: { count: 145, label: 'ROV' },
  freefire: { count: 98, label: 'Free Fire' },
  efootball: { count: 67, label: 'eFootball' },
  pubg: { count: 82, label: 'PUBG' },
  genshin: { count: 156, label: 'Genshin Impact' },
  roblox: { count: 213, label: 'Roblox' },
  other: { count: 45, label: 'Other' },
}

// ==================== Roblox Products ====================
export const robloxProducts: Product[] = [
  {
    id: 'rblx-1',
    sellerId: 'user-2',
    sellerName: 'ร้าน TopSeller',
    title: 'Roblox Robux 4,500 R$',
    description: 'Robux 4,500 R$ ราคาถูก ส่งไวภายใน 5 นาที เติมผ่านกลุ่ม Payout ปลอดภัย 100%',
    price: 1290,
    originalPrice: 1800,
    category: 'roblox',
    type: 'topup',
    status: 'available',
    images: ['https://images.unsplash.com/photo-1640955014216-75201056c829?w=400&h=300&fit=crop'],
    details: {
      'จำนวน Robux': '4,500 R$',
      'วิธีส่ง': 'กลุ่ม Payout',
      'เวลาส่ง': 'ภายใน 5 นาที',
      'แพลตฟอร์ม': 'PC / Mobile / Xbox',
    },
    tags: ['roblox', 'robux', 'topup', 'เติม robux'],
    views: 3420,
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-03-15T08:00:00Z',
  },
  {
    id: 'rblx-2',
    sellerId: 'user-2',
    sellerName: 'ร้าน TopSeller',
    title: 'Roblox Account Premium - Limiteds หายาก',
    description: 'บัญชี Roblox Premium มี Limited items หายากมูลค่ากว่า 50,000 R$ อายุบัญชี 5+ ปี',
    price: 5500,
    originalPrice: 8000,
    category: 'roblox',
    type: 'account',
    status: 'available',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop'],
    details: {
      'อายุบัญชี': '5 ปี+',
      'Premium': 'ใช่',
      'Limited Items': '15+ ชิ้น',
      'มูลค่า Limiteds': '50,000+ R$',
      'Robux คงเหลือ': '1,200 R$',
    },
    tags: ['roblox', 'limited', 'premium', 'account', 'ไอดีหายาก'],
    views: 2150,
    createdAt: '2024-02-15T10:00:00Z',
    updatedAt: '2024-03-10T08:00:00Z',
  },
  {
    id: 'rblx-3',
    sellerId: 'user-2',
    sellerName: 'ร้าน TopSeller',
    title: 'Roblox Robux 800 R$ (ราคาประหยัด)',
    description: 'Robux 800 R$ ราคาประหยัด เหมาะสำหรับผู้เริ่มต้น ส่งไวปลอดภัย',
    price: 290,
    originalPrice: 450,
    category: 'roblox',
    type: 'topup',
    status: 'available',
    images: ['https://images.unsplash.com/photo-1616588589676-62b3bd4ff6d2?w=400&h=300&fit=crop'],
    details: {
      'จำนวน Robux': '800 R$',
      'วิธีส่ง': 'กลุ่ม Payout',
      'เวลาส่ง': 'ภายใน 5 นาที',
    },
    tags: ['roblox', 'robux', 'topup', 'ถูก'],
    views: 5680,
    createdAt: '2024-03-05T10:00:00Z',
    updatedAt: '2024-03-14T08:00:00Z',
  },
]
